trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

variables:
  backendKey: 'terraform.tfstate'
  azureServiceConnection: 'azurerm'
  approvalEmail: 'intx.contact@gmail.com'

stages:
  # Dev Stage
  - stage: Dev
    displayName: 'Dev Environment'
    jobs:
      - template: terraform-template.yml
        parameters:
          environmentName: 'dev'
          backendRG: 'dev-dove-rg'
          backendSA: 'devdovetfstateblaze2322'
          backendKey: $(backendKey)
          azureServiceConnection: $(azureServiceConnection)
          approvalEmail: $(approvalEmail)

  # Test Stage
  - stage: Test
    displayName: 'Test Environment'
    dependsOn: Dev
    jobs:
      - template: terraform-template.yml
        parameters:
          environmentName: 'test'
          backendRG: 'test-goose-rg'
          backendSA: 'testgoosetfstateblaze2'
          backendKey: $(backendKey)
          azureServiceConnection: $(azureServiceConnection)
          approvalEmail: $(approvalEmail)

  # Prod Stage
  - stage: Prod
    displayName: 'Prod Environment'
    dependsOn: Test
    jobs:
      - template: terraform-template.yml
        parameters:
          environmentName: 'prod'
          backendRG: 'prod-wildcat-rg'
          backendSA: 'prodwildcattfstateblaze2'
          backendKey: $(backendKey)
          azureServiceConnection: $(azureServiceConnection)
          approvalEmail: $(approvalEmail)
